const SET_INQUIRIES_LIST = 'SET_INQUIRIES_LIST';
const SET_INQUIRIES_INFO = 'SET_INQUIRIES_INFO';
const SELECT_INQUIRIES = 'SELECT_INQUIRIES';
const NEW_INQUIRIES = 'NEW_INQUIRIES';

const SET_INQUIRIES_SUCCESS = 'SET_INQUIRIES_SUCCESS';

export default {
  SET_INQUIRIES_LIST,
  SET_INQUIRIES_INFO,
  SELECT_INQUIRIES,
  NEW_INQUIRIES,
  SET_INQUIRIES_SUCCESS
};
