const SET_INQUIRIES_LIST = 'SET_INQUIRIES_LIST';
const SELECT_INQUIRIES = 'SELECT_INQUIRIES';
const NEW_INQUIRIES = 'NEW_INQUIRIES';

export default {
  SET_INQUIRIES_LIST,
  SELECT_INQUIRIES,
  NEW_INQUIRIES,
};
