const RESET_STATE = 'RESET_STATE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT = 'LOGOUT';
const CHANGE_USER_TYPE = 'CHANGE_USER_TYPE';
export default {
  RESET_STATE,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_ERROR,
  LOGOUT,
  CHANGE_USER_TYPE
};
