const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT = 'LOGOUT';
const SET_CODE = 'SET_CODE';
const FEEDBACK_DIRECT = 'FEEDBACK_DIRECT';
const TOMORROW_DIRECT = 'TOMORROW_DIRECT';
export default {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_ERROR,
  LOGOUT,
  SET_CODE,
  FEEDBACK_DIRECT,
  TOMORROW_DIRECT,
};