// 초기화
const RESET_STATE = 'RESET_STATE';
// 사이즈 데이터
const SET_SIZES_DATA = 'SET_SIZES_DATA';
// 선호스타일 데이터
const SET_PREFERRED_STYLE_DATA = 'SET_PREFERRED_STYLE_DATA';
// 유저 정보 데이터
const SET_USER_INFO_DATA = 'SET_USER_INFO_DATA';
// 결제 정보 데이터
const SET_PAYMENT_INFO_DATA = 'SET_PAYMENT_INFO_DATA';
// 아직 미정 데이터 지워질수도 있음.
const SET_MEMBERSHIP_DATA = 'SET_MEMBERSHIP_DATA';

export default {
  RESET_STATE,
  SET_SIZES_DATA,
  SET_PREFERRED_STYLE_DATA,
  SET_USER_INFO_DATA,
  SET_PAYMENT_INFO_DATA,
  SET_MEMBERSHIP_DATA
};