const MEMBER_COUNT = 'MEMBER_COUNT';
const MEMBER_STYLE_TYPE = 'MEMBER_STYLE_TYPE';
const MEMBER_STYLE = 'MEMBER_STYLE';
const GET_MYPAGE = 'GET_MYPAGE';
const POST_PHONE = 'POST_PHONE';
const PATCH_PHONE = 'PATCH_PHONE';

export default {
  MEMBER_COUNT,
  MEMBER_STYLE_TYPE,
  MEMBER_STYLE,
  GET_MYPAGE,
  POST_PHONE,
  PATCH_PHONE
};
