const MEMBER_COUNT = 'MEMBER_COUNT';
const MEMBER_STYLE_TYPE = 'MEMBER_STYLE_TYPE';
const MEMBER_STYLE = 'MEMBER_STYLE';
const GET_MYPAGE = 'GET_MYPAGE';

export default {
  MEMBER_COUNT,
  MEMBER_STYLE_TYPE,
  MEMBER_STYLE,
  GET_MYPAGE
};
