const MEMBER_COUNT = 'MEMBER_COUNT';
const MEMBER_STYLE_TYPE = 'MEMBER_STYLE_TYPE';
const MEMBER_STYLE = 'MEMBER_STYLE';
const GET_MYPAGE = 'GET_MYPAGE';
const POST_PHONE = 'POST_PHONE';
const PATCH_PHONE = 'PATCH_PHONE';
const PATCH_PAYMENT = 'PATCH_PAYMENT';
const PATCH_ADDRESS = 'PATCH_ADDRESS';
const PATCH_LOBBY_PASSWORD = 'PATCH_LOBBY_PASSWORD';
const PATCH_ANN = 'PATCH_ANN';
const PATCH_PASSWORD = 'PATCH_PASSWORD';

export default {
  MEMBER_COUNT,
  MEMBER_STYLE_TYPE,
  MEMBER_STYLE,
  GET_MYPAGE,
  POST_PHONE,
  PATCH_PHONE,
  PATCH_PAYMENT,
  PATCH_ADDRESS,
  PATCH_LOBBY_PASSWORD,
  PATCH_ANN,
  PATCH_PASSWORD
};
