const RESET_STATE = 'RESET_STATE';
const GET_INQUIRIES_SUCCESS = 'GET_INQUIRIES_SUCCESS';
const GET_INQUIRIES_FAILED = 'GET_INQUIRIES_FAILED';
const GET_INQUIRIES_DETAIL = 'GET_INQUIRIES_DETAIL';

const POST_INQUIRIES = 'POST_INQUIRIES';
export default {
  RESET_STATE,
  GET_INQUIRIES_SUCCESS,
  GET_INQUIRIES_FAILED,
  GET_INQUIRIES_DETAIL,
  POST_INQUIRIES
};
