const GET_INQUIRIES_SUCCESS = 'GET_INQUIRIES_SUCCESS';
const GET_INQUIRIES_FAILED = 'GET_INQUIRIES_FAILED';
const GET_INQUIRIES_DETAIL = 'GET_INQUIRIES_DETAIL';
export default {
  GET_INQUIRIES_SUCCESS,
  GET_INQUIRIES_FAILED,
  GET_INQUIRIES_DETAIL
};
