const POST_PASSWORD = 'POST_PASSWORD';
const DESTROY_PASSWORD_AUTH = 'DESTROY_PASSWORD_AUTH';
const POST_FIND_ID = 'POST_FIND_ID';
const POST_FIND_ID_AUTH = 'POST_FIND_ID_AUTH';
const DESTROY_FIND_ID_AUTH = 'DESTROY_FIND_ID_AUTH';

const POST_FIND_PWD = 'POST_FIND_PWD';
const POST_FIND_PWD_AUTH = 'POST_FIND_PWD_AUTH';
const DESTROY_FIND_PW_AUTH = 'DESTROY_FIND_PW_AUTH';

export default {
  POST_PASSWORD,
  DESTROY_PASSWORD_AUTH,
  POST_FIND_ID,
  POST_FIND_ID_AUTH,
  DESTROY_FIND_ID_AUTH,
  POST_FIND_PWD,
  POST_FIND_PWD_AUTH,
  DESTROY_FIND_PW_AUTH
};
