const MYPAGE_SECURITY = 'MYPAGE_SECURITY';
const MYPAGE_SECURITY_DESTROYED = 'MYPAGE_SECURITY_DESTROYED';
const MYPAGE_LOAD = 'MYPAGE_LOAD';
const MYPAGE_CHANGE_EMAIL = 'MYPAGE_CHANGE_EMAIL';
const MYPAGE_CHANGE_PASSWORD = 'MYPAGE_CHANGE_PASSWORD';
const MYPAGE_CHANGE_PAYMENT = 'MYPAGE_CHANGE_PAYMENT';

const PHONE_VERIFY = 'PHONE_VERIFY';
const PHONE_VERIFY_CHECK = 'PHONE_VERIFY_CHECK';
const PHONE_VERIFY_COUNT = 'PHONE_VERIFY_COUNT';

const SET_MEMBER_STYLE = 'SET_MEMBER_STYLE';

export default {
  MYPAGE_SECURITY,
  MYPAGE_SECURITY_DESTROYED,
  MYPAGE_LOAD,
  MYPAGE_CHANGE_EMAIL,
  MYPAGE_CHANGE_PASSWORD,
  MYPAGE_CHANGE_PAYMENT,
  PHONE_VERIFY,
  PHONE_VERIFY_CHECK,
  PHONE_VERIFY_COUNT,
  SET_MEMBER_STYLE,
};
