const MYPAGE_SECURITY = 'MYPAGE_SECURITY';
const MYPAGE_SECURITY_DESTROYED = 'MYPAGE_SECURITY_DESTROYED';
const MYPAGE_LOAD = 'MYPAGE_LOAD';
const MYPAGE_CHANGE_EMAIL = 'MYPAGE_CHANGE_EMAIL';

export default {
  MYPAGE_SECURITY,
  MYPAGE_SECURITY_DESTROYED,
  MYPAGE_LOAD,
  MYPAGE_CHANGE_EMAIL,
};
