const SET_PAST_CLOSET = 'SET_PAST_CLOSET';
const SET_PAST_DETAIL_VIEW = 'SET_PAST_DETAIL_VIEW';
const SET_PARENT_NONE = 'SET_PARENT_NONE';

const SET_CURRENT_CLOSET = 'SET_CURRENT_CLOSET';
const SET_CURRENT_NONE = 'SET_CURRENT_NONE';

const SET_TOMORROW_CLOSET = 'SET_TOMORROW_CLOSET';
const SET_TOMORROW_NONE = 'SET_TOMORROW_NONE';
const SET_TOMORROW_SELECT = 'SET_TOMORROW_SELECT';

const INIT_PAYMENT_CURRENT = 'INIT_PAYMENT_CURRENT';
const PAYMENT_CURRENT = 'PAYMENT_CURRENT';

export default {
  SET_PAST_CLOSET,
  SET_PAST_DETAIL_VIEW,
  SET_PARENT_NONE,
  SET_CURRENT_CLOSET,
  SET_CURRENT_NONE,
  SET_TOMORROW_CLOSET,
  SET_TOMORROW_NONE,
  SET_TOMORROW_SELECT,
  INIT_PAYMENT_CURRENT,
  PAYMENT_CURRENT,
};
