const SET_PAST_CLOSET = 'SET_PAST_CLOSET';
const SET_PAST_DETAIL_VIEW = 'SET_PAST_DETAIL_VIEW';

const SET_CURRENT_CLOSET = 'SET_CURRENT_CLOSET';

export default {
  SET_PAST_CLOSET,
  SET_PAST_DETAIL_VIEW,
  SET_CURRENT_CLOSET,
};
