const RESET_STATE = 'RESET_STATE';
/* [ 내일의 옷장 ] */
const SET_TOMORROW_DATA = 'SET_TOMORROW_DATA';
const SET_TOMORROW_DATA_EXIST = 'SET_TOMORROW_DATA_EXIST';
const SET_TOMORROW_SELECTED = 'SET_TOMORROW_SELECTED';
const SET_TOMORROW_DIRECT_STATE = 'SET_TOMORROW_DIRECT_STATE';
/* [ 현재의 옷장 ] */
const SET_CURRENT_DATA = 'SET_CURRENT_DATA';
const SET_CURRENT_DATA_EXIST = 'SET_CURRENT_DATA_EXIST';
const SET_CURRENT_FEEDBACK_STATE = 'SET_CURRENT_FEEDBACK_STATE';
const SET_CURRENT_FEEDBACK_DIRECT_STATE = 'SET_CURRENT_FEEDBACK_DIRECT_STATE';
const SET_CURRENT_FEEDBACK_DATA = 'SET_CURRENT_FEEDBACK_DATA';

/* [ 과거의 옷장 ] */
const SET_PAST_DATA = 'SET_PAST_DATA';
const SET_PAST_DATA_EXIST = 'SET_PAST_DATA_EXIST';
const SET_PAST_FEEDBACK_DATA = 'SET_PAST_FEEDBACK_DATA';

/* [ 구독 정보 ] */
const SET_SUBSCRIPTION_DATA = 'SET_SUBSCRIPTION_DATA';

/* [ FAQ ] */
const SET_FAQ_DATA = 'SET_FAQ_DATA';
const SET_FAQ_TYPES = 'SET_FAQ_TYPES';

/* [ 공지사항 ] */
const SET_NOTICES_DATA = 'SET_NOTICES_DATA';

const SET_DIRECT_ACCESS_FAILURE = 'SET_DIRECT_ACCESS_FAILURE';
export default {
  RESET_STATE,

  SET_TOMORROW_DATA,
  SET_TOMORROW_DATA_EXIST,
  SET_TOMORROW_SELECTED,
  SET_TOMORROW_DIRECT_STATE,

  SET_CURRENT_DATA,
  SET_CURRENT_DATA_EXIST,
  SET_CURRENT_FEEDBACK_STATE,
  SET_CURRENT_FEEDBACK_DIRECT_STATE,
  SET_CURRENT_FEEDBACK_DATA,

  SET_PAST_DATA,
  SET_PAST_DATA_EXIST,
  SET_PAST_FEEDBACK_DATA,

  SET_SUBSCRIPTION_DATA,

  SET_FAQ_DATA,
  SET_FAQ_TYPES,

  SET_NOTICES_DATA,

  SET_DIRECT_ACCESS_FAILURE
};
