const RESET_STATE = 'RESET_STATE';
/* [ 내일의 옷장 ] */
const SET_TOMORROW_DATA = 'SET_TOMORROW_DATA';
const SET_TOMORROW_DATA_EXIST = 'SET_TOMORROW_DATA_EXIST';
const SET_TOMORROW_SELECTED = 'SET_TOMORROW_SELECTED';
const SET_TOMORROW_DIRECT_STATE = 'SET_TOMORROW_DIRECT_STATE';
/* [ 현재의 옷장 ] */
const SET_CURRENT_DATA = 'SET_CURRENT_DATA';
const SET_CURRENT_DATA_EXIST = 'SET_CURRENT_DATA_EXIST';
const SET_CURRENT_FEEDBACK_STATE = 'SET_CURRENT_FEEDBACK_STATE';
const SET_CURRENT_FEEDBACK_DIRECT_STATE = 'SET_CURRENT_FEEDBACK_DIRECT_STATE';
const SET_CURRENT_FEEDBACK_DATA = 'SET_CURRENT_FEEDBACK_DATA';

const SET_DIRECT_ACCESS_FAILURE = 'SET_DIRECT_ACCESS_FAILURE';
export default {
  RESET_STATE,

  SET_TOMORROW_DATA,
  SET_TOMORROW_DATA_EXIST,
  SET_TOMORROW_SELECTED,
  SET_TOMORROW_DIRECT_STATE,

  SET_CURRENT_DATA,
  SET_CURRENT_DATA_EXIST,
  SET_CURRENT_FEEDBACK_STATE,
  SET_CURRENT_FEEDBACK_DIRECT_STATE,
  SET_CURRENT_FEEDBACK_DATA,

  SET_DIRECT_ACCESS_FAILURE
};
