const GET_SIZES = "GET_SIZES";
const GET_FIRST_DELIVERY_DAYS = "GET_FIRST_DELIVERY_DAYS";
const GET_OPTIONS = 'GET_OPTIONS';

export default {
  GET_SIZES,
  GET_FIRST_DELIVERY_DAYS,
  GET_OPTIONS
};
