const SET_SIGNUP_FIRST_DATA = 'SET_SIGNUP_FIRST_DATA';
const SET_SIGNUP_SIZE = 'SET_SIGNUP_SIZE';
const PHONE_VERIFY = 'PHONE_VERIFY';
const PHONE_VERIFY_CHECK = 'PHONE_VERIFY_CHECK';
const PHONE_VERIFY_COUNT = 'PHONE_VERIFY_COUNT';

const SET_COLORS = 'SET_COLORS';
const PICK_COLORS = 'PICK_COLORS';
const PICK_REMOVE_COLORS = 'PICK_REMOVE_COLORS';
const SET_REQUIREMENT = 'SET_REQUIREMENT';

const SET_CLOTHES = 'SET_CLOTHES';
const PICK_CLOTHES = 'PICK_CLOTHES';
const PICK_REMOVE_CLOTHES = 'PICK_REMOVE_CLOTHES';
const SET_MANAGEMENT = 'SET_MANAGEMENT';
const PICK_MANAGEMENT = 'PICK_MANAGEMENT';
const PICK_REMOVE_MANAGEMENT = 'PICK_REMOVE_MANAGEMENT';

const PICK_MOOD = 'PICK_MOOD';

export default {
  SET_SIGNUP_FIRST_DATA,
  SET_SIGNUP_SIZE,
  PHONE_VERIFY,
  PHONE_VERIFY_CHECK,
  PHONE_VERIFY_COUNT,
  SET_COLORS,
  PICK_COLORS,
  PICK_REMOVE_COLORS,
  SET_REQUIREMENT,
  SET_CLOTHES,
  PICK_CLOTHES,
  PICK_REMOVE_CLOTHES,
  SET_MANAGEMENT,
  PICK_MANAGEMENT,
  PICK_REMOVE_MANAGEMENT,
  PICK_MOOD,
};
