const SET_SIGNUP_FIRST_DATA = 'SET_SIGNUP_FIRST_DATA';
const PHONE_VERIFY = 'PHONE_VERIFY';
const PHONE_VERIFY_CHECK = 'PHONE_VERIFY_CHECK';
const PHONE_VERIFY_COUNT = 'PHONE_VERIFY_COUNT';

export default {
  SET_SIGNUP_FIRST_DATA,
  PHONE_VERIFY,
  PHONE_VERIFY_CHECK,
  PHONE_VERIFY_COUNT,
};
