const RESET_STATE = 'RESET_STATE';
const SET_SIZES = 'SET_SIZES';
const SET_OPTIONS = 'SET_OPTIONS';

const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export default {
  RESET_STATE,
  SET_SIZES,
  SET_OPTIONS,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGIN_ERROR,
  LOGOUT_SUCCESS
};
