const PHONE_VERIFY = 'PHONE_VERIFY';
const PHONE_VERIFY_CHECK = 'PHONE_VERIFY_CHECK';
const PHONE_VERIFY_COUNT = 'PHONE_VERIFY_COUNT';
const PHONE_VERIFY_PWD = 'PHONE_VERIFY_PWD';
const PHONE_VERIFY_CHECK_PWD = 'PHONE_VERIFY_CHECK_PWD';
const PHONE_VERIFY_COUNT_PWD = 'PHONE_VERIFY_COUNT_PWD';
const PHONE_VERIFY_PWD_COMPLETE = 'PHONE_VERIFY_PWD_COMPLETE';

export default {
  PHONE_VERIFY,
  PHONE_VERIFY_CHECK,
  PHONE_VERIFY_COUNT,
  PHONE_VERIFY_PWD,
  PHONE_VERIFY_CHECK_PWD,
  PHONE_VERIFY_COUNT_PWD,
  PHONE_VERIFY_PWD_COMPLETE
};
