const RESET_STATE = 'RESET_STATE';
const SET_SIZES = 'SET_SIZES';
const PHONE_VERIFY = 'PHONE_VERIFY';
const PHONE_VERIFY_CHECK = 'PHONE_VERIFY_CHECK';
const TOGGLE_MAIN_BANNER = 'TOGGLE_MAIN_BANNER';
const CHECK_CURRENT_ROUTE = 'CHECK_CURRENT_ROUTE';
const SUCCESS_RESTART = 'SUCCESS_RESTART';
const RESET_RESTART = 'RESET_RESTART';

export default {
  RESET_STATE,
  SET_SIZES,
  PHONE_VERIFY,
  PHONE_VERIFY_CHECK,
  TOGGLE_MAIN_BANNER,
  CHECK_CURRENT_ROUTE,
  SUCCESS_RESTART,
  RESET_RESTART
};
