const RESET_STATE = 'RESET_STATE';
const GET_FAQ = 'GET_FAQ';
const GET_FAQ_MAIN_LIST = 'GET_FAQ_MAIN_LIST';
const GET_FAQ_TYPES = 'GET_FAQ_TYPES';

export default {
  RESET_STATE,
  GET_FAQ,
  GET_FAQ_MAIN_LIST,
  GET_FAQ_TYPES
};
