const RESET_STATE = 'RESET_STATE';

const GET_TOMORROW = 'GET_TOMORROW';
const PUT_TOMORROW = 'PUT_TOMORROW';
const GET_TOMORROW_DIRECT = 'GET_TOMORROW_DIRECT';
const DESTROY_TOMORROW_DIRECT = 'DESTROY_TOMORROW_DIRECT';
const GET_TOMORROW_PRODUCT_DETAIL = 'GET_TOMORROW_PRODUCT_DETAIL';

const GET_CURRENT = 'GET_CURRENT';
const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'; // 삭제 예정
const GET_CURRENT_FEEDBACKS = 'GET_CURRENT_FEEDBACKS';
const GET_CURRENT_FEEDBACKS_DIRECT = 'GET_CURRENT_FEEDBACKS_DIRECT';
const DESTROY_CURRENT_FEEDBACKS_DIRECT = 'DESTROY_CURRENT_FEEDBACKS_DIRECT';

const GET_PAST_SUCCESS = 'GET_PAST_SUCCESS';
const GET_PAST_FAILED = 'GET_PAST_FAILED';
const GET_PAST_DETAIL = 'GET_PAST_DETAIL';
const GET_PAST_FEEDBACKS = 'GET_PAST_FEEDBACKS';
const GET_PAST_PRODUCT_DETAIL = 'GET_PAST_PRODUCT_DETAIL';

export default {
  RESET_STATE,

  GET_TOMORROW,
  PUT_TOMORROW,
  GET_TOMORROW_DIRECT,
  DESTROY_TOMORROW_DIRECT,
  GET_TOMORROW_PRODUCT_DETAIL,

  GET_CURRENT,
  GET_PRODUCT_DETAIL,
  GET_CURRENT_FEEDBACKS,
  GET_CURRENT_FEEDBACKS_DIRECT,
  DESTROY_CURRENT_FEEDBACKS_DIRECT,

  GET_PAST_SUCCESS,
  GET_PAST_FAILED,
  GET_PAST_DETAIL,
  GET_PAST_FEEDBACKS,
  GET_PAST_PRODUCT_DETAIL
};
