const GET_CURRENT = 'GET_CURRENT';
const GET_TOMORROW = 'GET_TOMORROW';
const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
const GET_CURRENT_FEEDBACKS = 'GET_CURRENT_FEEDBACKS';
const GET_CURRENT_FEEDBACKS_DIRECT = 'GET_CURRENT_FEEDBACKS_DIRECT';
export default {
  GET_CURRENT,
  GET_TOMORROW,
  GET_PRODUCT_DETAIL,
  GET_CURRENT_FEEDBACKS,
  GET_CURRENT_FEEDBACKS_DIRECT
};
